In [1]:
import numpy as np

In [2]:
A = np.zeros((3,3))

In [3]:
A

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [4]:
# G(V,E) with a matrix representation
class G:
    def __init__(self, n):
        self.V = n
        self.M = np.zeros((n,n))

In [54]:
g = G(8)

In [55]:
g.M[0][1] = 1
g.M[0][2] = 1
g.M[1][3] = 1
g.M[1][4] = 1
g.M[2][5] = 1
g.M[2][6] = 1
g.M[3][7] = 1
g.M[3][0] = 1
g.M[4][7] = 1
g.M[4][0] = 1
g.M[5][0] = 1
g.M[6][0] = 1
g.M[7][0] = 1

In [81]:
# G.M stores in (i,j) the number of times both words were adjacent

class TextRank:
    def __init__(self, G, it=20, damping=0.85, tolerance=None):
        self.n = G.V
        self.M = G.M
        self.it = it
        self.tolerance=tolerance
        self.alpha = damping
        self.S = np.ones((1, self.n))
        self.p = np.ones((1, self.n))
        self.p = self.p / self.n
    
    def initialize(self):
        self.S = self.S / self.n
        M_row_sum = np.sum(self.M, 1).reshape(self.n, 1)
        self.M_norm = self.M / M_row_sum
    
    def update(self):
        S = self.alpha * np.matmul(self.S, self.M_norm) + (1 - self.alpha) * self.p
        diff = np.sum(np.abs(S - self.S))
        self.S = S
        return diff
        
        
    def compute(self):
        self.initialize()
        
        if self.tolerance is None:
            for i in range(self.it):
                self.update()
            return self.it
        else:
            num_iterations = 0
            diff = float("inf")
            while diff > self.tolerance:
                diff = self.update()
                num_iterations += 1
            return num_iterations


In [82]:
text_rank = TextRank(g, it=100, tolerance=1e-6)
it = text_rank.compute()
print(it)

0.6375
0.541875
0.46059375
0.358879296875
0.22185265625
0.188574757812
0.135243459119
0.095797450209
0.0814278326777
0.053063804295
0.0451042336507
0.0363938870798
0.0227878518146
0.0193696740424
0.0139476707256
0.00973457844452
0.00827439167784
0.00540262305781
0.00459222959914
0.00372360241254
0.00233559057931
0.00198525199242
0.00143721390742
0.000988929019867
0.000840589666887
0.000549886560477
0.000467403576406
0.000380865067423
0.000239310536321
0.000203413955873
0.000148043199073
0.000100431590463
8.53668518933e-05
5.59509685421e-05
4.75583232607e-05
3.89451415858e-05
2.4513148209e-05
2.08361759777e-05
1.52442169509e-05
1.01960265772e-05
8.66662259057e-06
5.69124069576e-06
4.83755459142e-06
3.98116190989e-06
2.51020432537e-06
2.13367367655e-06
1.56918300627e-06
1.0347727902e-06
8.79556871738e-07
49


In [21]:
row_sum = np.sum(g.M,1).reshape(g.V, 1)
#np.shape(row_sum)
row_sum

array([[ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [36]:
M_ = g.M / row_sum
M_

array([[ 0. ,  0.5,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0.5,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0.5,  0.5,  0. ],
       [ 0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5],
       [ 0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [27]:
S = np.ones((1, g.V))
S = S/g.V

In [28]:
S

array([[ 0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125]])

In [37]:
S1 = np.matmul(S, M_)
S1

array([[ 0.5   ,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,  0.0625,
         0.125 ]])

In [38]:
S2 = np.matmul(S1, M_)
S2

array([[ 0.3125 ,  0.25   ,  0.25   ,  0.03125,  0.03125,  0.03125,
         0.03125,  0.0625 ]])

In [46]:
2000/25

80.0

In [50]:
0.0625 * 4

0.25